In [1]:
import pandas as pd

In [2]:
# Imports
dados1 = pd.read_parquet('../data/raw/3m/transaction-01.snappy.parquet')
dados2 = pd.read_parquet('../data/raw/3m/transaction-02.snappy.parquet')
dados3 = pd.read_parquet('../data/raw/3m/transaction-03.snappy.parquet')
dados4 = pd.read_parquet('../data/raw/3m/transaction-04.snappy.parquet')

In [23]:
# Conferindo se os dados estão corretos
dados1.info(), dados2.info(), dados3.info(), dados4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3556632 entries, 0 to 3556631
Data columns (total 71 columns):
 #   Column                             Dtype
---  ------                             -----
 0   transaction_id                     int32
 1   app_origin                         int32
 2   device_id                          object
 3   store_id                           float64
 4   payable_id                         int32
 5   type                               object
 6   status                             int32
 7   created_at                         object
 8   updated_at                         object
 9   finished_at                        object
 10  finished_at_local                  object
 11  transaction_reference_code         object
 12  invoice_id                         object
 13  payer_id                           float64
 14  payout_batch_id                    object
 15  payout_id                          object
 16  payout_status                      object
 17  payment_partner_id                 object
 18  payment_option_id                  object
 19  payment_detail                     object
 20  payout_partner_id                  object
 21  payment_status                     object
 22  gross_payment_in_cents             int32
 23  payment_transaction_id             object
 24  payment_result_json                object
 25  payout_result_json                 object
 26  payment_result_do_cancel           object
 27  payment_data_request               object
 28  payout_data_request                object
 29  gas_type_id                        object
 30  quantity_in_litres                 float32
 31  nozzle_id                          int32
 32  price_per_litre                    float32
 33  total_in_cents                     int32
 34  total_discont_in_cents             int32
 35  voucher_id                         object
 36  fueling_status                     object
 37  volume_totalizer                   float32
 38  braintree_data                     object
 39  device_gcm                         object
 40  controller_raw_finished_at         object
 41  controller_finished_at             object
 42  penelope_finished_at               object
 43  fueling_finished_at                object
 44  attendant_id                       object
 45  session_id                         float64
 46  pump_id                            float64
 47  consumer_id                        float64
 48  ltm_result_json                    float64
 49  ltm_request_json                   float64
 50  credit_account_id                  float64
 51  credits_result_json                object
 52  credits_data_request               object
 53  credits_transaction_id             float64
 54  credits_total_in_cents             int32
 55  credits_refund_result_json         object
 56  credits_refund_data_request        object
 57  credits_refund_result_code         float64
 58  credits_refund_result_description  object
 59  credits_result_code                float64
 60  credits_result_description         object
 61  credits_end_balance_in_cents       float64
 62  reward_id                          float64
 63  reward_discount                    float64
 64  pos_id                             float64
 65  accumulated_discount_99_in_cents   int32
 66  voucher_discount                   float64
 67  payout_date                        object
 68  datalake_dt                        object
 69  year_ptt                           int32
 70  day_ptt                            int32
dtypes: float32(3), float64(16), int32(12), object(40)
memory usage: 1.7+ GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3640298 entries, 0 to 3640297
Data columns (total 71 columns):
 #   Column                             Dtype
---  ------                             -----
 0   transaction_id                     int32
 1   app_origin                         int32
 2   device_id                          object
 3   store_id                           float64
 4   payable_id                         int32
 5   type                               object
 6   status                             int32
 7   created_at                         object
 8   updated_at                         object
 9   finished_at                        object
 10  finished_at_local                  object
 11  transaction_reference_code         object
 12  invoice_id                         object
 13  payer_id                           float64
 14  payout_batch_id                    object
 15  payout_id                          object
 16  payout_status                      object
 17  payment_partner_id                 object
 18  payment_option_id                  object
 19  payment_detail                     object
 20  payout_partner_id                  object
 21  payment_status                     object
 22  gross_payment_in_cents             int32
 23  payment_transaction_id             object
 24  payment_result_json                object
 25  payout_result_json                 object
 26  payment_result_do_cancel           object
 27  payment_data_request               object
 28  payout_data_request                object
 29  gas_type_id                        object
 30  quantity_in_litres                 float32
 31  nozzle_id                          int32
 32  price_per_litre                    float32
 33  total_in_cents                     int32
 34  total_discont_in_cents             int32
 35  voucher_id                         object
 36  fueling_status                     object
 37  volume_totalizer                   float32
 38  braintree_data                     object
 39  device_gcm                         object
 40  controller_raw_finished_at         object
 41  controller_finished_at             object
 42  penelope_finished_at               object
 43  fueling_finished_at                object
 44  attendant_id                       object
 45  session_id                         float64
 46  pump_id                            float64
 47  consumer_id                        float64
 48  ltm_result_json                    float64
 49  ltm_request_json                   float64
 50  credit_account_id                  float64
 51  credits_result_json                object
 52  credits_data_request               object
 53  credits_transaction_id             float64
 54  credits_total_in_cents             int32
 55  credits_refund_result_json         object
 56  credits_refund_data_request        object
 57  credits_refund_result_code         float64
 58  credits_refund_result_description  object
 59  credits_result_code                float64
 60  credits_result_description         object
 61  credits_end_balance_in_cents       float64
 62  reward_id                          float64
 63  reward_discount                    float64
 64  pos_id                             float64
 65  accumulated_discount_99_in_cents   int32
 66  voucher_discount                   float64
 67  payout_date                        object
 68  datalake_dt                        object
 69  year_ptt                           int32
 70  day_ptt                            int32
dtypes: float32(3), float64(16), int32(12), object(40)
memory usage: 1.7+ GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3578472 entries, 0 to 3578471
Data columns (total 71 columns):
 #   Column                             Dtype
---  ------                             -----
 0   transaction_id                     int32
 1   app_origin                         int32
 2   device_id                          object
 3   store_id                           float64
 4   payable_id                         int32
 5   type                               object
 6   status                             int32
 7   created_at                         object
 8   updated_at                         object
 9   finished_at                        object
 10  finished_at_local                  object
 11  transaction_reference_code         object
 12  invoice_id                         object
 13  payer_id                           float64
 14  payout_batch_id                    object
 15  payout_id                          object
 16  payout_status                      object
 17  payment_partner_id                 object
 18  payment_option_id                  object
 19  payment_detail                     object
 20  payout_partner_id                  object
 21  payment_status                     object
 22  gross_payment_in_cents             int32
 23  payment_transaction_id             object
 24  payment_result_json                object
 25  payout_result_json                 object
 26  payment_result_do_cancel           object
 27  payment_data_request               object
 28  payout_data_request                object
 29  gas_type_id                        object
 30  quantity_in_litres                 float32
 31  nozzle_id                          int32
 32  price_per_litre                    float32
 33  total_in_cents                     int32
 34  total_discont_in_cents             int32
 35  voucher_id                         object
 36  fueling_status                     object
 37  volume_totalizer                   float32
 38  braintree_data                     object
 39  device_gcm                         object
 40  controller_raw_finished_at         object
 41  controller_finished_at             object
 42  penelope_finished_at               object
 43  fueling_finished_at                object
 44  attendant_id                       object
 45  session_id                         float64
 46  pump_id                            float64
 47  consumer_id                        float64
 48  ltm_result_json                    float64
 49  ltm_request_json                   float64
 50  credit_account_id                  float64
 51  credits_result_json                object
 52  credits_data_request               object
 53  credits_transaction_id             float64
 54  credits_total_in_cents             int32
 55  credits_refund_result_json         object
 56  credits_refund_data_request        object
 57  credits_refund_result_code         float64
 58  credits_refund_result_description  object
 59  credits_result_code                float64
 60  credits_result_description         object
 61  credits_end_balance_in_cents       float64
 62  reward_id                          float64
 63  reward_discount                    float64
 64  pos_id                             float64
 65  accumulated_discount_99_in_cents   int32
 66  voucher_discount                   float64
 67  payout_date                        object
 68  datalake_dt                        object
 69  year_ptt                           int32
 70  day_ptt                            int32
dtypes: float32(3), float64(16), int32(12), object(40)
memory usage: 1.7+ GB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1537764 entries, 0 to 1537763
Data columns (total 71 columns):
 #   Column                             Non-Null Count    Dtype
---  ------                             --------------    -----
 0   transaction_id                     1537764 non-null  int32
 1   app_origin                         1537764 non-null  int32
 2   device_id                          1531488 non-null  object
 3   store_id                           1531488 non-null  float64
 4   payable_id                         1537764 non-null  int32
 5   type                               1537764 non-null  object
 6   status                             1537764 non-null  int32
 7   created_at                         1537764 non-null  object
 8   updated_at                         1537764 non-null  object
 9   finished_at                        1531488 non-null  object
 10  finished_at_local                  1531488 non-null  object
 11  transaction_reference_code         1537764 non-null  object
 12  invoice_id                         1531488 non-null  object
 13  payer_id                           45218 non-null    float64
 14  payout_batch_id                    6256 non-null     object
 15  payout_id                          302055 non-null   object
 16  payout_status                      1333255 non-null  object
 17  payment_partner_id                 1502594 non-null  object
 18  payment_option_id                  1502269 non-null  object
 19  payment_detail                     1502610 non-null  object
 20  payout_partner_id                  302063 non-null   object
 21  payment_status                     1486714 non-null  object
 22  gross_payment_in_cents             1537764 non-null  int32
 23  payment_transaction_id             634163 non-null   object
 24  payment_result_json                1456008 non-null  object
 25  payout_result_json                 302063 non-null   object
 26  payment_result_do_cancel           0 non-null        object
 27  payment_data_request               1273498 non-null  object
 28  payout_data_request                302063 non-null   object
 29  gas_type_id                        1526019 non-null  object
 30  quantity_in_litres                 1537764 non-null  float32
 31  nozzle_id                          1537764 non-null  int32
 32  price_per_litre                    1537764 non-null  float32
 33  total_in_cents                     1537764 non-null  int32
 34  total_discont_in_cents             1537764 non-null  int32
 35  voucher_id                         279216 non-null   object
 36  fueling_status                     1531488 non-null  object
 37  volume_totalizer                   1526019 non-null  float32
 38  braintree_data                     0 non-null        object
 39  device_gcm                         991528 non-null   object
 40  controller_raw_finished_at         198233 non-null   object
 41  controller_finished_at             0 non-null        object
 42  penelope_finished_at               198233 non-null   object
 43  fueling_finished_at                1526019 non-null  object
 44  attendant_id                       1523375 non-null  object
 45  session_id                         0 non-null        float64
 46  pump_id                            1526019 non-null  float64
 47  consumer_id                        1531488 non-null  float64
 48  ltm_result_json                    0 non-null        float64
 49  ltm_request_json                   0 non-null        float64
 50  credit_account_id                  0 non-null        float64
 51  credits_result_json                29606 non-null    object
 52  credits_data_request               29606 non-null    object
 53  credits_transaction_id             29606 non-null    float64
 54  credits_total_in_cents             1537764 non-null  int32
 55  credits_refund_result_json         304 non-null      object
 56  credits_refund_data_request        304 non-null      object
 57  credits_refund_result_code         0 non-null        float64
 58  credits_refund_result_description  0 non-null        object
 59  credits_result_code                0 non-null        float64
 60  credits_result_description         0 non-null        object
 61  credits_end_balance_in_cents       1333255 non-null  float64
 62  reward_id                          304545 non-null   float64
 63  reward_discount                    1339531 non-null  float64
 64  pos_id                             0 non-null        float64
 65  accumulated_discount_99_in_cents   1537764 non-null  int32
 66  voucher_discount                   1339531 non-null  float64
 67  payout_date                        302058 non-null   object
 68  datalake_dt                        1537764 non-null  object
 69  year_ptt                           1537764 non-null  int32
 70  day_ptt                            1537764 non-null  int32
dtypes: float32(3), float64(16), int32(12), object(40)
memory usage: 745.0+ MB

(None, None, None, None)

In [11]:
# Count para ver se estamos puxando todos os dados
dados1.count(), dados2.count()

(transaction_id      3556632
 app_origin          3556632
 device_id           3549953
 store_id            3549953
 payable_id          3556632
                      ...
 voucher_discount    3102324
 payout_date         1187230
 datalake_dt         3556632
 year_ptt            3556632
 day_ptt             3556632
 Length: 71, dtype: int64,
 transaction_id      3640298
 app_origin          3640298
 device_id           3639994
 store_id            3639994
 payable_id          3640298
                      ...
 voucher_discount    3214759
 payout_date         1410306
 datalake_dt         3640298
 year_ptt            3640298
 day_ptt             3640298
 Length: 71, dtype: int64)

In [16]:
# Concatenando todos os datasets
full_transactions = pd.concat([dados1, dados2, dados3, dados4], ignore_index=True)

In [7]:
dados1.shape[0] + dados2.shape[0] + dados3.shape[0] + dados4.shape[0]

12313166

In [17]:
full_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12313166 entries, 0 to 12313165
Data columns (total 71 columns):
 #   Column                             Dtype
---  ------                             -----
 0   transaction_id                     int32
 1   app_origin                         int32
 2   device_id                          object
 3   store_id                           float64
 4   payable_id                         int32
 5   type                               object
 6   status                             int32
 7   created_at                         object
 8   updated_at                         object
 9   finished_at                        object
 10  finished_at_local                  object
 11  transaction_reference_code         object
 12  invoice_id                         object
 13  payer_id                           float64
 14  payout_batch_id                    object
 15  payout_id                          object
 16  payout_status                      object
 17  payment_partner_id                 object
 18  payment_option_id                  object
 19  payment_detail                     object
 20  payout_partner_id                  object
 21  payment_status                     object
 22  gross_payment_in_cents             int32
 23  payment_transaction_id             object
 24  payment_result_json                object
 25  payout_result_json                 object
 26  payment_result_do_cancel           object
 27  payment_data_request               object
 28  payout_data_request                object
 29  gas_type_id                        object
 30  quantity_in_litres                 float32
 31  nozzle_id                          int32
 32  price_per_litre                    float32
 33  total_in_cents                     int32
 34  total_discont_in_cents             int32
 35  voucher_id                         object
 36  fueling_status                     object
 37  volume_totalizer                   float32
 38  braintree_data                     object
 39  device_gcm                         object
 40  controller_raw_finished_at         object
 41  controller_finished_at             object
 42  penelope_finished_at               object
 43  fueling_finished_at                object
 44  attendant_id                       object
 45  session_id                         float64
 46  pump_id                            float64
 47  consumer_id                        float64
 48  ltm_result_json                    float64
 49  ltm_request_json                   float64
 50  credit_account_id                  float64
 51  credits_result_json                object
 52  credits_data_request               object
 53  credits_transaction_id             float64
 54  credits_total_in_cents             int32
 55  credits_refund_result_json         object
 56  credits_refund_data_request        object
 57  credits_refund_result_code         float64
 58  credits_refund_result_description  object
 59  credits_result_code                float64
 60  credits_result_description         object
 61  credits_end_balance_in_cents       float64
 62  reward_id                          float64
 63  reward_discount                    float64
 64  pos_id                             float64
 65  accumulated_discount_99_in_cents   int32
 66  voucher_discount                   float64
 67  payout_date                        object
 68  datalake_dt                        object
 69  year_ptt                           int32
 70  day_ptt                            int32
dtypes: float32(3), float64(16), int32(12), object(40)
memory usage: 5.8+ GB

In [18]:
#Salvando em Parquet
full_transactions.to_parquet('full_transactions.parquet')

In [21]:
dados1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3556632 entries, 0 to 3556631
Data columns (total 71 columns):
 #   Column                             Dtype
---  ------                             -----
 0   transaction_id                     int32
 1   app_origin                         int32
 2   device_id                          object
 3   store_id                           float64
 4   payable_id                         int32
 5   type                               object
 6   status                             int32
 7   created_at                         object
 8   updated_at                         object
 9   finished_at                        object
 10  finished_at_local                  object
 11  transaction_reference_code         object
 12  invoice_id                         object
 13  payer_id                           float64
 14  payout_batch_id                    object
 15  payout_id                          object
 16  payout_status                      object
 17  payment_partner_id                 object
 18  payment_option_id                  object
 19  payment_detail                     object
 20  payout_partner_id                  object
 21  payment_status                     object
 22  gross_payment_in_cents             int32
 23  payment_transaction_id             object
 24  payment_result_json                object
 25  payout_result_json                 object
 26  payment_result_do_cancel           object
 27  payment_data_request               object
 28  payout_data_request                object
 29  gas_type_id                        object
 30  quantity_in_litres                 float32
 31  nozzle_id                          int32
 32  price_per_litre                    float32
 33  total_in_cents                     int32
 34  total_discont_in_cents             int32
 35  voucher_id                         object
 36  fueling_status                     object
 37  volume_totalizer                   float32
 38  braintree_data                     object
 39  device_gcm                         object
 40  controller_raw_finished_at         object
 41  controller_finished_at             object
 42  penelope_finished_at               object
 43  fueling_finished_at                object
 44  attendant_id                       object
 45  session_id                         float64
 46  pump_id                            float64
 47  consumer_id                        float64
 48  ltm_result_json                    float64
 49  ltm_request_json                   float64
 50  credit_account_id                  float64
 51  credits_result_json                object
 52  credits_data_request               object
 53  credits_transaction_id             float64
 54  credits_total_in_cents             int32
 55  credits_refund_result_json         object
 56  credits_refund_data_request        object
 57  credits_refund_result_code         float64
 58  credits_refund_result_description  object
 59  credits_result_code                float64
 60  credits_result_description         object
 61  credits_end_balance_in_cents       float64
 62  reward_id                          float64
 63  reward_discount                    float64
 64  pos_id                             float64
 65  accumulated_discount_99_in_cents   int32
 66  voucher_discount                   float64
 67  payout_date                        object
 68  datalake_dt                        object
 69  year_ptt                           int32
 70  day_ptt                            int32
dtypes: float32(3), float64(16), int32(12), object(40)
memory usage: 1.7+ GB